[versions]
agp = "8.11.0"
gson = "2.13.1"
kotlin = "2.1.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
loggingInterceptor = "4.12.0"
material = "1.12.0"
moshi = "3.0.0"
moshiKotlin = "1.15.2"
neuronet = "1.0.5"
retrofit = "3.0.0"
roomRuntimeAndroid = "2.7.2"
workRuntimeKtx = "2.10.2"
ksp_version = "2.1.21-2.0.1"
kotlinxSerializationJson = "1.9.0"
activity = "1.10.1"
constraintlayout = "2.2.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "moshi" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
neuronet = { module = "com.github.Greenhorn2025:neuronet", version.ref = "neuronet" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }


#androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntimeAndroid" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntimeAndroid" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeAndroid" }


kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_version" }
android-library = { id = "com.android.library", version.ref = "agp" }